{"name": "test_login_successfully", "status": "failed", "statusDetails": {"message": "AssertionError: login failed", "trace": "self = <tests.test_login.LoginTest testMethod=test_login_successfully>\n\n    @allure.story('epic_1') # epic/story of the test case\n    @allure.severity(allure.severity_level.MINOR) # severity of the test case\n    # @pytestrail.case('C48') # test case if on TestRail\n    def test_login_successfully(self):\n        with allure.step('Navigate to login page'):\n            self.homeNavigation.goToLoginPage()\n            self.ts.markFinal(self.loginPage.isAt, \"navigation to login page failed\")\n    \n        with allure.step('Login'):\n            self.loginPage.login(email=td.testData(\"email\"), password=td.testData(\"password\"))\n>           self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n\ntests\\test_login.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x0000021B09FC89D0>, result = False, resultMessage = 'login failed'\n\n    def markFinal(self, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n        if \"FAIL\" in self.resultList:\n            self.resultList.clear()\n>           assert False, resultMessage\nE           AssertionError: login failed\n\nutilities\\teststatus.py:54: AssertionError"}, "steps": [{"name": "Navigate to login page", "status": "passed", "start": 1686795489788, "stop": 1686795490425}, {"name": "Login", "status": "failed", "statusDetails": {"message": "AssertionError: login failed\n", "trace": "  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\tests\\test_login.py\", line 36, in test_login_successfully\n    self.ts.markFinal(self.loggedInPage.isAt, \"login failed\")\n  File \"D:\\Python Frameworks selenium\\Python-Test-Automation-Framework\\utilities\\teststatus.py\", line 54, in markFinal\n    assert False, resultMessage\n"}, "attachments": [{"name": "login failed.1686795550591.png", "source": "fc89bc78-f154-463e-ab36-ed95f59e02f6-attachment.png", "type": "image/png"}], "start": 1686795490426, "stop": 1686795550986}], "attachments": [{"name": "log", "source": "5a0f18b1-c711-4f1f-8ccf-d5586d53e8c0-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d31d9fe1-1d05-4d96-8838-4acd05a9a2f9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "83c40837-4ef0-4995-b5d0-414831fa0b7b-attachment.txt", "type": "text/plain"}], "start": 1686795489788, "stop": 1686795550988, "uuid": "1095e83f-597e-47b4-b5a2-b78fc36a8001", "historyId": "e9f4bee14a43cc6ef574959b962f5cb7", "testCaseId": "e9f4bee14a43cc6ef574959b962f5cb7", "fullName": "tests.test_login.LoginTest#test_login_successfully", "labels": [{"name": "severity", "value": "minor"}, {"name": "story", "value": "epic_1"}, {"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-Q4MGKFU"}, {"name": "thread", "value": "25216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}